dist: trusty

language: android

jdk:
  - oraclejdk8

before_install:
    - yes | sdkmanager "platforms;android-30"
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  ./gradlew clean build